#!/usr/bin/env python3
"""
AGSIST -- copy the static crawlable header/footer into every root page.

WHY THIS EXISTS
components/loader.js fetches components/header.html and footer.html on
DOMContentLoaded and swaps them in with
    document.getElementById('site-header').replaceWith(fragment)
so a crawler that does not run JS (Bing, most AI crawlers, link checkers) saw
an empty <div id="site-header"></div> on ~50 pages: 3-20 links per page and no
site structure. Nine pages carried a hand-pasted static nav INSIDE that div --
which replaceWith() throws away on a JS load, so it never duplicates the live
nav -- and those nine copies had already drifted from each other.

This script makes components/header-fallback.html and footer-fallback.html the
single source and copies them inside #site-header / #site-footer of every
public root page, between markers. It also puts the two above-the-fold font
preloads in each <head> (measured 2026-10-06 with Playwright on index, markets,
breakeven, cash-rent, about, corn-futures-prices, tools: Inter 400 and
JetBrains Mono 700 cover the most above-the-fold text and load on every page).

Edit the fallback files, then run this. Idempotent.

    python3 scripts/inject_static_nav.py           # write
    python3 scripts/inject_static_nav.py --check   # exit 1 if any page is stale

SKIPPED: meta-refresh stubs, and
pages without the #site-header / #site-footer placeholders (embedded snippets,
sponsor-report). Subdirectory pages (rent/, farmland-atlas/, daily/, basis/,
hail-map/) are generated by their own builders and are not touched here.
"""
import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
COMP = REPO / "components"
SKIP = set()

FONTS = ("/fonts/inter-400.woff2", "/fonts/jetbrains-mono-700.woff2")
FONT_BLOCK = ("<!-- static-nav:fonts (scripts/inject_static_nav.py) -->\n"
              + "".join(f'  <link rel="preload" href="{u}" as="font" type="font/woff2" crossorigin>\n'
                        for u in FONTS)
              + "  <!-- /static-nav:fonts -->")
FONT_RE = re.compile(r"<!-- static-nav:fonts .*?<!-- /static-nav:fonts -->", re.S)
REFRESH_RE = re.compile(r'<meta[^>]+http-equiv=["\']refresh["\']', re.I)
DIV_TAG_RE = re.compile(r"<div\b|</div\s*>", re.I)


def block(kind):
    body = (COMP / f"{kind}-fallback.html").read_text(encoding="utf-8").rstrip("\n")
    return (f"\n<!-- static-nav:{kind} (scripts/inject_static_nav.py; source "
            f"components/{kind}-fallback.html) -->\n{body}\n<!-- /static-nav:{kind} -->\n")


def fill_div(html, div_id, inner, page):
    """Replace everything inside <div id=div_id>...</div> (nesting-aware)."""
    m = re.search(rf'<div\s+id="{div_id}"[^>]*>', html)
    if not m:
        return None
    depth, pos = 1, m.end()
    for t in DIV_TAG_RE.finditer(html, pos):
        depth += -1 if t.group(0).startswith("</") else 1
        if depth == 0:
            return html[:m.end()] + inner + html[t.start():]
    raise SystemExit(f"{page}: unbalanced <div id=\"{div_id}\">")


def fill_fonts(html):
    if FONT_RE.search(html):
        return FONT_RE.sub(lambda _: FONT_BLOCK, html, count=1)
    head_end = html.find("</head>")
    # Ahead of the stylesheet so the font requests start in parallel with it.
    m = re.search(r'<link\s+rel="(?:preload|stylesheet)"[^>]*components/styles\.css', html[:head_end])
    at = m.start() if m else head_end
    return html[:at] + FONT_BLOCK + "\n  " + html[at:]


def eligible(path, html):
    if path.name in SKIP or REFRESH_RE.search(html):
        return False
    return 'id="site-header"' in html and 'id="site-footer"' in html


def render(html, page, hdr, ftr):
    out = fill_div(html, "site-header", hdr, page)
    out = fill_div(out, "site-footer", ftr, page)
    return fill_fonts(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if any page would change")
    a = ap.parse_args()
    hdr, ftr = block("header"), block("footer")
    stale, done, skipped = [], 0, []
    for p in sorted(REPO.glob("*.html")):
        html = p.read_text(encoding="utf-8")
        if not eligible(p, html):
            skipped.append(p.name)
            continue
        new = render(html, p.name, hdr, ftr)
        assert render(new, p.name, hdr, ftr) == new, f"{p.name}: not idempotent"
        if new != html:
            stale.append(p.name)
            if not a.check:
                p.write_text(new, encoding="utf-8")
        done += 1
    if a.check:
        if stale:
            print(f"STALE ({len(stale)}): {', '.join(stale)} -- run scripts/inject_static_nav.py")
            return 1
        print(f"OK: {done} pages carry the current static nav + font preloads")
        return 0
    print(f"updated {len(stale)} of {done} pages; skipped {len(skipped)}: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
